#!/bin/bash
#
# if LightBurn update feature does not work, try installing libssl1.0-dev
#sudo apt install libssl1.0-dev

HERE=`pwd`

lbDIR=~/.local/share/LightBurn

if [ "$1" == "" ] ; then
  #echo :$1: parm DOES NOT exist
  lbCMD=$lbDIR/LightBurn
else
  if [ -f $1 ] ; then
    #echo parm exists, file exists
    lbCMD="$lbDIR/LightBurn $1"
  else
    echo parm exists, file $1 does not exist
    lbCMD=$lbDIR/LightBurn
  fi
fi

lbLibsDIR=~/LightBurnLibs
gstLibs=gstreamer-1.0

if [ ! -d $lbLibsDIR/$gstLibs ] ; then
  cd
  git clone http://github.com/dlarue/LightBurnLibs
  cd $HERE
fi

GST_PLUGIN_SYSTEM_PATH=${lbLibsDIR}/${gstLibs} $lbCMD
